keys:
  - &users:
    - &cristi_yubikey 09B0879FFEF55E7B046E58C7AEF4A543011E8AC1
    - &w9098_ssh_key age1ut96p7m37gsh5fgua8cvl6m723gp358qfxtx6dehl99yshmmmcqqv72m7v
    - &lab_wsl_ssh_key age1xgw7z066dzzs5c5v599w77t0ygd2tepdq8jxu5kwrre3q3z2j3xq9xqkx4
  - &hosts:
    - &precision_ssh_key age1hxnc4mz9j6rrz7rf69y3y7llv6gncr9fd85608hj8tql9rgnw57s4kyvga
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
        - *cristi_yubikey
      age:
        - *w9098_ssh_key
        - *precision_ssh_key
        - *lab_wsl_ssh_key
