keys:
  - &users:
    - &cristi_yubikey 09B0879FFEF55E7B046E58C7AEF4A543011E8AC1
    - &w9098_ssh_key age1ds5ql4ztngt9pul8ghsux9rkle6wnxgt0l33enun8namv3795uwq60tyvq
  - &hosts:
    - &precision_ssh_key age1hxnc4mz9j6rrz7rf69y3y7llv6gncr9fd85608hj8tql9rgnw57s4kyvga
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
        - *cristi_yubikey
      age:
        - *w9098_ssh_key
        - *precision_ssh_key
