# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      inputs.disko.nixosModules.disko
      ./disko-config.nix
      #../common/optional/encrypted-root.nix
      #../common/optional/ephemeral-btrfs.nix
    ];

  hardware.graphics.enable = true;
  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;

    #---------------------------------------------------------------------
    # Install additional packages that improve graphics performance and compatibility.
    #---------------------------------------------------------------------
    extraPackages = with pkgs; [
      intel-media-driver      # LIBVA_DRIVER_NAME=iHD
      mesa.drivers
      vaapiIntel                  # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
      vaapiVdpau
      libvdpau-va-gl
      vulkan-validation-layers
   ];
  };

  hardware.enableAllFirmware = lib.mkDefault true;

  boot.initrd = {
    availableKernelModules = [
      "thunderbolt"
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    kernelModules = [ "i915" ];
  };

  # vhost_vsock: Enables the capacity to launch vm with a virtual socket (network)
  boot.kernelModules = [
    "kvm"
    "kvm-intel"
    "acpi_call"
    "vhost_vsock"
  ];

  # Bootloader.
  boot.loader.efi.canTouchEfiVariables = true;

  # TODO Setup keyfile
  #boot.initrd.secrets = {
  #  "/crypto_keyfile.bin" = null;
  #};

  # ip forwarding is needed for NAT'ing to work.
  boot.kernel.sysctl = {
    "net.ipv4.conf.all.forwarding" = true;
    "net.ipv4.conf.default.forwarding" = true;
  };

  boot.kernelParams = [
    #"mem_sleep_default=s2idle"
  ];

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;

  # ==================================================================================
  # Quality of Life changes
  # ==================================================================================

  # Perhaps similar issue as described here: https://github.com/NixOS/nixos-hardware/blob/master/dell/xps/15-9510/default.nix#L11
  # and here: https://github.com/NixOS/nixos-hardware/blob/master/dell/xps/15-9520/default.nix#L12
  #boot.extraModprobeConfig = ''
  #  options iwlwifi 11n_disable=8
  #  options iwlwifi power_save=1 disable_11ax=1
  #'';

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        # A2DP profile enable for bluetooth
        Enable = "Source,Sink,Media,Socket";
        # Show battery status
        Experimental = true;
      };
    };
  };
}
